# Generated by Django 5.1.5 on 2025-01-17 07:20

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Афиша. Индексная страница событий',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventTagIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Индекс тегов событий',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date_on', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('h1', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('h2', models.CharField(blank=True, max_length=256, verbose_name='Подзаголовок')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Основная чвсть')),
                ('founder', models.CharField(blank=True, max_length=256, verbose_name='Организатор')),
                ('location', models.CharField(blank=True, max_length=256, verbose_name='Место проведения')),
                ('is_for_slider', models.BooleanField(default=False, help_text='На домашней странице слайдер с самыми актуальными событиями. Поля выше отобразятся в слайдере.', verbose_name='Включить в слайдер')),
                ('image', models.ForeignKey(blank=True, help_text='Постер (1304x483)px, 2,7/1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Событие',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventTagPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tegged_items', to='event.eventpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eventpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='event.EventTagPage', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
