# Generated by Django 5.1.5 on 2025-01-17 07:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailvideos', '0015_video_height_video_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('slogan', models.CharField(blank=True, help_text='Текст на фоне видео', max_length=255, verbose_name='Слоган на видео')),
                ('button_register', models.CharField(blank=True, help_text='Регистрация', max_length=16, verbose_name='Кнопка регистрации')),
                ('button_info', models.CharField(blank=True, help_text='Подробнее', max_length=16, verbose_name='Кнопка информации')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('link_info', models.ForeignKey(blank=True, help_text='Выбрать страницу, для перехода по кнопке', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Hero ссылка "Подробнее"')),
                ('link_register', models.ForeignKey(blank=True, help_text='Выбрать страницу, для перехода по кнопке', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Hero ссылка для регистрации')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailvideos.video', verbose_name='Видео секции HERO')),
            ],
            options={
                'verbose_name': 'Домашняя страница',
            },
            bases=('wagtailcore.page',),
        ),
    ]
