# Generated by Django 5.1.3 on 2024-12-17 09:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailvideos', '0015_video_height_video_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_text', models.CharField(blank=True, help_text='Слоган на фоне видео', max_length=255)),
                ('hero_button', models.CharField(blank=True, help_text='Текст кнопки', max_length=16, verbose_name='Текст кнопки')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('hero_link', models.ForeignKey(blank=True, help_text='Выбрать страницу, для перехода по кнопке на фоне видео', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Hero ссылка')),
                ('hero_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailvideos.video')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
