# Generated by Django 5.1.5 on 2025-01-17 07:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('image_block', 7), ('embded_block', 8), ('card', 11), ('featured_posts', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Текст заголовка', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Выбрать размер заголовка'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'label': 'Уровень', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Параграф'}), 4: ('wagtail.images.blocks.ImageBlock', [], {'label': 'Изображение'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Название', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Будет через тире после названия', 'label': 'Расшифровка', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 6)]], {'label': 'Изображение'}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Ввести URL для встраивания, например, https://rutube.ru/video/da422a2520db8cc2705357e858aaba98/', 'icon': 'media', 'label': 'Встроенный блок'}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Содержание'}), 11: ('wagtail.blocks.StructBlock', [[('heading', 9), ('text', 10), ('image', 4)]], {'group': 'Блоки портфолио'}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Содержание', 'required': False}), 13: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['blog.BlogPage']}), 14: ('wagtail.blocks.ListBlock', (13,), {'label': 'Записи блога'}), 15: ('wagtail.blocks.StructBlock', [[('heading', 9), ('text', 12), ('posts', 14)]], {'group': 'Блоки портфолио'})}, help_text="Используйте '+' чтобы выбрать тип блока и добавить содержимое")),
            ],
            options={
                'verbose_name': 'Внутренняя страница',
            },
            bases=('wagtailcore.page',),
        ),
    ]
