# Generated by Django 5.1.3 on 2025-01-18 06:27

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Учреждения',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LocationIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Объекты',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TrainerIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Тренеры',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InstitutionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('site', models.CharField(blank=True, max_length=512, verbose_name='Сайт')),
                ('logo', models.ForeignKey(blank=True, help_text='Логотип', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Учреждение',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LocationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institutionpage', verbose_name='Уреждение')),
            ],
            options={
                'verbose_name': 'Объект',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='TrainerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('name2', models.CharField(blank=True, max_length=64, null=True, verbose_name='Отчество')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('education', models.CharField(blank=True, max_length=128, null=True, verbose_name='Образование')),
                ('ranks', models.CharField(blank=True, max_length=128, null=True, verbose_name='Звания и достижения')),
                ('foto', models.ForeignKey(blank=True, help_text='Фотография', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer', to='institution.institutionpage', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Тренер',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TrainerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category', models.CharField(choices=[('Тренер высшей квалификационной категории', 'Тренер высшей квалификационной категории'), ('Тренер первой квалификационной категории', 'Тренер первой квалификационной категории'), ('Тренер второй квалификационной категории', 'Тренер второй квалификационной категории')], max_length=256, verbose_name='Категория')),
                ('end_date', models.DateField(blank=True, help_text='Введите дату', verbose_name='Срок до')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='institution.trainerpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
