# Generated by Django 5.1.3 on 2025-01-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstitutionInexPage',
            new_name='InstitutionIndexPage',
        ),
    ]
