# Generated by Django 5.1.3 on 2025-01-16 10:13

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_trainerindexpage_trainerpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpage',
            name='institution',
            field=modelcluster.fields.ParentalKey(default=18, on_delete=django.db.models.deletion.PROTECT, related_name='institution', to='institution.institutionpage', verbose_name='Организация'),
            preserve_default=False,
        ),
    ]
