# Generated by Django 5.1.3 on 2025-01-16 11:44

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_trainerpage_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerpage',
            name='institution',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainer', to='institution.institutionpage', verbose_name='Организация'),
        ),
    ]
